//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coach
    {
        public int CoachID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string College { get; set; }
        public Nullable<int> Age { get; set; }
        public string DOB { get; set; }
        public Nullable<int> Experience { get; set; }
        public string OffPhil { get; set; }
        public string DefPhil { get; set; }
        public Nullable<int> LoyaltyPlayers { get; set; }
        public Nullable<int> LoyaltyCoaches { get; set; }
        public Nullable<int> Ego { get; set; }
        public Nullable<int> OffAbility { get; set; }
        public Nullable<int> DefAbility { get; set; }
        public Nullable<int> Stability { get; set; }
        public Nullable<int> DevPlayers { get; set; }
        public Nullable<int> JudgingAct { get; set; }
        public Nullable<int> JudgingPot { get; set; }
        public Nullable<int> JudgingQB { get; set; }
        public Nullable<int> JudgingRB { get; set; }
        public Nullable<int> JudgingRec { get; set; }
        public Nullable<int> JudgingOL { get; set; }
        public Nullable<int> JudgingDL { get; set; }
        public Nullable<int> JudgingLB { get; set; }
        public Nullable<int> JudgingCB { get; set; }
        public Nullable<int> JudgingSF { get; set; }
        public Nullable<int> Accountability { get; set; }
        public Nullable<int> Motivating { get; set; }
        public Nullable<int> TimeMgmt { get; set; }
        public Nullable<int> Clutch { get; set; }
        public Nullable<int> Conservative { get; set; }
        public Nullable<int> FBInt { get; set; }
        public Nullable<int> Adjustments { get; set; }
        public Nullable<int> ValuesST { get; set; }
        public Nullable<int> ValuesCharacter { get; set; }
        public Nullable<int> WorkEthic { get; set; }
        public Nullable<int> Preparation { get; set; }
        public Nullable<int> Focus { get; set; }
        public Nullable<int> PlaycallingSkill { get; set; }
    }
}
