//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GM
    {
        public int GMID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string College { get; set; }
        public Nullable<int> Age { get; set; }
        public string DOB { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> CoachPatience { get; set; }
        public Nullable<int> Risktaker { get; set; }
        public Nullable<int> ValuesDraftPicks { get; set; }
        public Nullable<int> ValuesCombine { get; set; }
        public Nullable<int> ValuesCharacter { get; set; }
        public Nullable<int> ValuesProduction { get; set; }
        public Nullable<int> FranchiseTag { get; set; }
        public Nullable<int> JudgingDraft { get; set; }
        public Nullable<int> JudgingFA { get; set; }
        public Nullable<int> JudgingOwn { get; set; }
        public Nullable<int> JudgingQB { get; set; }
        public Nullable<int> JudgingRB { get; set; }
        public Nullable<int> JudgingRec { get; set; }
        public Nullable<int> JudgingOL { get; set; }
        public Nullable<int> JudgingDL { get; set; }
        public Nullable<int> JudgingLB { get; set; }
        public Nullable<int> JudgingCB { get; set; }
        public Nullable<int> JudgingSF { get; set; }
        public Nullable<int> Loyalty { get; set; }
        public Nullable<int> Ego { get; set; }
        public string OffPhil { get; set; }
        public Nullable<int> QBImp { get; set; }
        public Nullable<int> RBImp { get; set; }
        public Nullable<int> FBImp { get; set; }
        public Nullable<int> WRImp { get; set; }
        public Nullable<int> WR2Imp { get; set; }
        public Nullable<int> WR3Imp { get; set; }
        public Nullable<int> LTImp { get; set; }
        public Nullable<int> LGImp { get; set; }
        public Nullable<int> CImp { get; set; }
        public Nullable<int> RGImp { get; set; }
        public Nullable<int> RTImp { get; set; }
        public Nullable<int> TEImp { get; set; }
        public string DefPhil { get; set; }
        public Nullable<int> DEImp { get; set; }
        public Nullable<int> DE2Imp { get; set; }
        public Nullable<int> DTImp { get; set; }
        public Nullable<int> DT2Imp { get; set; }
        public Nullable<int> NTImp { get; set; }
        public Nullable<int> MLBImp { get; set; }
        public Nullable<int> WLBImp { get; set; }
        public Nullable<int> SLBImp { get; set; }
        public Nullable<int> ROLBImp { get; set; }
        public Nullable<int> LOLBImp { get; set; }
        public Nullable<int> CB1Imp { get; set; }
        public Nullable<int> CB2Imp { get; set; }
        public Nullable<int> CB3Imp { get; set; }
        public Nullable<int> FSImp { get; set; }
        public Nullable<int> SSImp { get; set; }
        public string DraftStrategy { get; set; }
        public string TeamBuilding { get; set; }
    }
}
