//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Owner
    {
        public int OwnerID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string College { get; set; }
        public Nullable<int> Age { get; set; }
        public string DOB { get; set; }
        public Nullable<int> OwnerRep { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<int> GMPatience { get; set; }
        public Nullable<int> CoachPatience { get; set; }
        public Nullable<int> Meddles { get; set; }
        public Nullable<int> WantsWinner { get; set; }
        public Nullable<int> SpendsMoney { get; set; }
    }
}
